// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Learning Numbers API
Prototpe Numbers API for learning purposes


    Schemes:
      http
    Host: localhost:9000
    BasePath: /v1
    Version: 0.0.1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
