// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Prototpe Numbers API for learning purposes",
    "title": "Learning Numbers API",
    "version": "0.0.1"
  },
  "host": "localhost:9000",
  "basePath": "/v1",
  "paths": {
    "/numbers": {
      "get": {
        "description": "Returns all stored numbers",
        "tags": [
          "number"
        ],
        "summary": "Returns numbers",
        "operationId": "getNumbers",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Number"
              }
            }
          },
          "500": {
            "description": "Something went wrong"
          }
        }
      },
      "post": {
        "description": "Add random numbers with specified count",
        "tags": [
          "number"
        ],
        "summary": "Add number",
        "operationId": "addNumbers",
        "parameters": [
          {
            "name": "count",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Count"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Invalid request"
          },
          "500": {
            "description": "Something went wrong"
          }
        }
      }
    }
  },
  "definitions": {
    "Count": {
      "description": "Number",
      "type": "object",
      "required": [
        "count"
      ],
      "properties": {
        "count": {
          "type": "integer"
        }
      },
      "example": {
        "count": 8
      }
    },
    "Number": {
      "description": "Number",
      "type": "object",
      "required": [
        "value"
      ],
      "properties": {
        "value": {
          "type": "integer"
        }
      },
      "example": {
        "value": 83657
      }
    }
  },
  "responses": {
    "200": {
      "description": "OK"
    },
    "400": {
      "description": "Invalid request"
    },
    "404": {
      "description": "Not found"
    },
    "500": {
      "description": "Something went wrong"
    }
  },
  "tags": [
    {
      "name": "number"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Prototpe Numbers API for learning purposes",
    "title": "Learning Numbers API",
    "version": "0.0.1"
  },
  "host": "localhost:9000",
  "basePath": "/v1",
  "paths": {
    "/numbers": {
      "get": {
        "description": "Returns all stored numbers",
        "tags": [
          "number"
        ],
        "summary": "Returns numbers",
        "operationId": "getNumbers",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Number"
              }
            }
          },
          "500": {
            "description": "Something went wrong"
          }
        }
      },
      "post": {
        "description": "Add random numbers with specified count",
        "tags": [
          "number"
        ],
        "summary": "Add number",
        "operationId": "addNumbers",
        "parameters": [
          {
            "name": "count",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Count"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Invalid request"
          },
          "500": {
            "description": "Something went wrong"
          }
        }
      }
    }
  },
  "definitions": {
    "Count": {
      "description": "Number",
      "type": "object",
      "required": [
        "count"
      ],
      "properties": {
        "count": {
          "type": "integer"
        }
      },
      "example": {
        "count": 8
      }
    },
    "Number": {
      "description": "Number",
      "type": "object",
      "required": [
        "value"
      ],
      "properties": {
        "value": {
          "type": "integer"
        }
      },
      "example": {
        "value": 83657
      }
    }
  },
  "responses": {
    "200": {
      "description": "OK"
    },
    "400": {
      "description": "Invalid request"
    },
    "404": {
      "description": "Not found"
    },
    "500": {
      "description": "Something went wrong"
    }
  },
  "tags": [
    {
      "name": "number"
    }
  ]
}`))
}
