// Code generated by go-swagger; DO NOT EDIT.

package number

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddNumbersHandlerFunc turns a function with the right signature into a add numbers handler
type AddNumbersHandlerFunc func(AddNumbersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddNumbersHandlerFunc) Handle(params AddNumbersParams) middleware.Responder {
	return fn(params)
}

// AddNumbersHandler interface for that can handle valid add numbers params
type AddNumbersHandler interface {
	Handle(AddNumbersParams) middleware.Responder
}

// NewAddNumbers creates a new http.Handler for the add numbers operation
func NewAddNumbers(ctx *middleware.Context, handler AddNumbersHandler) *AddNumbers {
	return &AddNumbers{Context: ctx, Handler: handler}
}

/*AddNumbers swagger:route POST /numbers number addNumbers

Add number

Add random numbers with specified count

*/
type AddNumbers struct {
	Context *middleware.Context
	Handler AddNumbersHandler
}

func (o *AddNumbers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddNumbersParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
