// Code generated by go-swagger; DO NOT EDIT.

package number

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddNumbersOKCode is the HTTP code returned for type AddNumbersOK
const AddNumbersOKCode int = 200

/*AddNumbersOK OK

swagger:response addNumbersOK
*/
type AddNumbersOK struct {
}

// NewAddNumbersOK creates AddNumbersOK with default headers values
func NewAddNumbersOK() *AddNumbersOK {

	return &AddNumbersOK{}
}

// WriteResponse to the client
func (o *AddNumbersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// AddNumbersBadRequestCode is the HTTP code returned for type AddNumbersBadRequest
const AddNumbersBadRequestCode int = 400

/*AddNumbersBadRequest Invalid request

swagger:response addNumbersBadRequest
*/
type AddNumbersBadRequest struct {
}

// NewAddNumbersBadRequest creates AddNumbersBadRequest with default headers values
func NewAddNumbersBadRequest() *AddNumbersBadRequest {

	return &AddNumbersBadRequest{}
}

// WriteResponse to the client
func (o *AddNumbersBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AddNumbersInternalServerErrorCode is the HTTP code returned for type AddNumbersInternalServerError
const AddNumbersInternalServerErrorCode int = 500

/*AddNumbersInternalServerError Something went wrong

swagger:response addNumbersInternalServerError
*/
type AddNumbersInternalServerError struct {
}

// NewAddNumbersInternalServerError creates AddNumbersInternalServerError with default headers values
func NewAddNumbersInternalServerError() *AddNumbersInternalServerError {

	return &AddNumbersInternalServerError{}
}

// WriteResponse to the client
func (o *AddNumbersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
