// Code generated by go-swagger; DO NOT EDIT.

package number

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "rest-api/models"
)

// GetNumbersOKCode is the HTTP code returned for type GetNumbersOK
const GetNumbersOKCode int = 200

/*GetNumbersOK OK

swagger:response getNumbersOK
*/
type GetNumbersOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Number `json:"body,omitempty"`
}

// NewGetNumbersOK creates GetNumbersOK with default headers values
func NewGetNumbersOK() *GetNumbersOK {

	return &GetNumbersOK{}
}

// WithPayload adds the payload to the get numbers o k response
func (o *GetNumbersOK) WithPayload(payload []*models.Number) *GetNumbersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get numbers o k response
func (o *GetNumbersOK) SetPayload(payload []*models.Number) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNumbersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Number, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetNumbersInternalServerErrorCode is the HTTP code returned for type GetNumbersInternalServerError
const GetNumbersInternalServerErrorCode int = 500

/*GetNumbersInternalServerError Something went wrong

swagger:response getNumbersInternalServerError
*/
type GetNumbersInternalServerError struct {
}

// NewGetNumbersInternalServerError creates GetNumbersInternalServerError with default headers values
func NewGetNumbersInternalServerError() *GetNumbersInternalServerError {

	return &GetNumbersInternalServerError{}
}

// WriteResponse to the client
func (o *GetNumbersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
